### ISSUE TITLE
Server error log after Uploaded PL3

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xpress-issues#210]
Server error log after Uploaded PL3. Now can not enter WP admin CP.

````
Error: Call to undefined method XPress::phrase() wordpress/wp-content/themes/wp-xpress-theme/inc/actions.php:51 

Generated by: Nirjonadda Aug 4, 2018 at 10:41 AM 

Stack trace

#0 wordpress/wp-includes/class-wp-hook.php(286): {closure}('')
#1 wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 wordpress/wp-includes/widgets.php(1649): do_action('widgets_init')
#4 wordpress/wp-includes/class-wp-hook.php(286): wp_widgets_init('')
#5 wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 wordpress/wp-settings.php(450): do_action('init')
#8 wordpress/wp-config.php(89): require_once('/home/nminfo/pu...')
#9 wordpress/wp-load.php(37): require_once('/home/nminfo/pu...')
#10 wordpress/wp-admin/admin.php(31): require_once('/home/nminfo/pu...')
#11 wordpress/wp-admin/index.php(10): require_once('/home/nminfo/pu...')
#12 {main}

Request state

array(4) {
  ["url"] => string(29) "/wordpress/wp-admin/index.php"
  ["referrer"] => string(58) "/admin.php?options/groups/thxpress/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by Nirjonadda** [comment]
Fixed after uploaded WP plugin files.
