### ISSUE TITLE
Automated navigation tab creation error

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#336]
```
TypeError: Argument 1 passed to XF\Navigation\Compiler::compileArrayValue() must be of the type array, null given, called in /home/demo/public_html/xf21/xlink/src/XF/Navigation/BasicType.php on line 76 src/XF/Navigation/Compiler.php:194
Generated by: admin Dec 11, 2018 at 3:59 PM
Stack trace
#0 src/XF/Navigation/BasicType.php(76): XF\Navigation\Compiler->compileArrayValue(NULL)
#1 src/XF/Entity/Navigation.php(193): XF\Navigation\BasicType->compileCode(Object(XF\Entity\Navigation), Object(XF\Navigation\Compiler))
#2 src/XF/Mvc/Entity/Entity.php(1285): XF\Entity\Navigation->_preSave()
#3 src/XF/Mvc/Entity/Entity.php(1138): XF\Mvc\Entity\Entity->preSave()
#4 src/addons/ThemeHouse/XLink/Entity/PlatformLink.php(74): XF\Mvc\Entity\Entity->save()
#5 src/XF/Mvc/Entity/Entity.php(1196): ThemeHouse\XLink\Entity\PlatformLink->_postSave()
#6 src/XF/Mvc/FormAction.php(69): XF\Mvc\Entity\Entity->save(true, false)
#7 src/XF/Mvc/FormAction.php(187): XF\Mvc\FormAction->XF\Mvc\{closure}(Object(XF\Mvc\FormAction))
#8 src/addons/ThemeHouse/XLink/Admin/Controller/Platform.php(137): XF\Mvc\FormAction->run()
#9 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\XLink\Admin\Controller\Platform->actionSave(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\XLin...', 'Save', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XLink\Admin\Controller\Platform), NULL)
#11 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XLink\Admin\Controller\Platform), NULL)
#12 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(2170): XF\Mvc\Dispatcher->run()
#14 src/XF.php(392): XF\App->run()
#15 admin.php(13): XF::runApp('XF\\Admin\\App')
#16 {main}
```

**Comment by LukasWieditz** [comment]
https://github.com/LukasWieditz/xf2/commit/a098d01cbdf305249ea49d44a1eed6880f46c797
