### ISSUE TITLE
ErrorException: [E_NOTICE] Undefined index: thxpress_username_sync

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xpress-issues#355]
````
ErrorException: [E_NOTICE] Undefined index: thxpress_username_sync src/addons/ThemeHouse/XPress/Setup/Patch1010000.php:46 

Generated by: Nirjonadda Dec 19, 2018 at 2:46 AM 

Stack trace

#0 src/addons/ThemeHouse/XPress/Setup/Patch1010000.php(46): XF::handlePhpError(8, '[E_NOTICE] Unde...', '/home/nminfo/pu...', 46, Array)
#1 src/XF/AddOn/StepRunnerUpgradeTrait.php(122): ThemeHouse\XPress\Setup->upgrade1000097Step2(Array)
#2 src/XF/AddOn/StepRunnerUpgradeTrait.php(71): ThemeHouse\XPress\Setup->upgradeStepRunner(1000097, 2, Array, 1000098)
#3 src/XF/Job/AddOnInstallBatch.php(293): ThemeHouse\XPress\Setup->upgrade(Array)
#4 src/XF/Job/AddOnInstallBatch.php(86): XF\Job\AddOnInstallBatch->stepAction(Object(XF\Timer))
#5 src/XF/Job/Manager.php(253): XF\Job\AddOnInstallBatch->run(G)
#6 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#7 src/XF/Job/Manager.php(111): XF\Job\Manager->runJobEntry(Array, G)
#8 src/XF/Admin/Controller/Tools.php(120): XF\Job\Manager->runByIds(Array, 8)
#9 src/XF/Mvc/Dispatcher.php(321): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#11 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#12 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#14 src/XF.php(392): XF\App->run()
#15 admin.php(13): XF::runApp('XF\\Admin\\App')
#16 {main}

Request state

array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(47) "/admin.php?tools/run-job"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(83) "/admin.php?add-ons/install-from-archive-complete&batch_id=21"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(3) "112"
  }
}
````

**Comment by LukasWieditz** [comment]
This is a follow-up error from #358
