### ISSUE TITLE
Error: Call to a member function findOldAccountLink() on null

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xpress-issues#357]
````
Error: Call to a member function findOldAccountLink() on null src/addons/ThemeHouse/XPress/Job/ImportUserLinks.php:66 

Generated by: Nirjonadda Dec 19, 2018 at 2:46 AM 

Stack trace

#0 src/XF/Job/Manager.php(253): ThemeHouse\XPress\Job\ImportUserLinks->run(G)
#1 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#2 src/XF/Job/Manager.php(111): XF\Job\Manager->runJobEntry(Array, G)
#3 src/XF/Admin/Controller/Tools.php(120): XF\Job\Manager->runByIds(Array, 8)
#4 src/XF/Mvc/Dispatcher.php(321): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#6 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#7 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#9 src/XF.php(392): XF\App->run()
#10 admin.php(13): XF::runApp('XF\\Admin\\App')
#11 {main}

Request state

array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(47) "/admin.php?tools/run-job"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(83) "/admin.php?add-ons/install-from-archive-complete&batch_id=21"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(7) "112,113"
  }
}
````

**Comment by LukasWieditz** [comment]
This is because XPress is not correctly installed on your site. Once the installation runs through, this will be resolved.
