### ISSUE TITLE
XWiki - Create account error

### ISSUE THREAD

**Issue by evertiro** [Audentio/xpress-issues#504]
I'm getting the following error about once an hour. Seems to me that even if it isn't the technical solution to the underlying problem, it'd be smart to at least check to see if the array key exists rather than just assuming that it does.

```
ErrorException: [E_NOTICE] Undefined index: user_createcount src/addons/ThemeHouse/XWiki/RemoteHandler/Account.php:113
```

```#0 src/addons/ThemeHouse/XWiki/RemoteHandler/Account.php(113): XF::handlePhpError(8, '[E_NOTICE] Unde...', '/var/www/vhosts...', 113, Array)
#1 src/addons/ThemeHouse/XLink/Entity/AccountLink.php(40): ThemeHouse\XWiki\RemoteHandler\Account->getRemoteStatistics()
#2 src/addons/ThemeHouse/XLink/Job/GetRemoteUserStatistics.php(72): ThemeHouse\XLink\Entity\AccountLink->refreshRemoteStats()
#3 src/XF/Job/Manager.php(253): ThemeHouse\XLink\Job\GetRemoteUserStatistics->run(G)
#4 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#5 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
#6 job.php(42): XF\Job\Manager->runQueue(false, 8)
#7 {main}```

**Comment by LukasWieditz** [comment]
Closed by https://github.com/LukasWieditz/xf2/commit/241ca4f27ef846a301ee3cbff3a017f1d6af285d
