### ISSUE TITLE
Sorry, comments are closed for this item error experienced

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#572]
Was reported by [Kirby](https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/post-1363157) on xenforo.com.

```
Exception: Sorry, comments are closed for this item. src/addons/ThemeHouse/XLink/RemoteHandler/Traits/APICall.php:78
Generated by: xxx Jul 17, 2019 at 3:17 PM
Stack trace
#0 src/addons/ThemeHouse/XPress/RemoteHandler/Entity.php(460): ThemeHouse\XPress\RemoteHandler\Entity->callAPI('/wp/v2/comments', Array, 'POST', false)
#1 src/addons/ThemeHouse/XPress/XF/Entity/Post.php(34): ThemeHouse\XPress\RemoteHandler\Entity->createComment(Object(XFMG\XF\Entity\Post))
#2 src/XF/Mvc/Entity/Entity.php(1208): ThemeHouse\XPress\XF\Entity\Post->_postSave()
#3 src/XF/Service/Thread/Replier.php(167): XF\Mvc\Entity\Entity->save(true, false)
#4 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Thread\Replier->_save()
#5 src/XF/Pub/Controller/Thread.php(461): XF\Service\Thread\Replier->save()
#6 src/XF/Mvc/Dispatcher.php(321): XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#7 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'AddReply', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XPress\XF\Pub\Controller\Thread), NULL)
#8 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XPress\XF\Pub\Controller\Thread), NULL)
#9 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#10 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#11 src/XF.php(390): XF\App->run()
#12 index.php(20): XF::runApp('XF\\Pub\\App')
#13 {main}
```

**Comment by LukasWieditz** [comment]
Nothing we can tackle. They'll have to make sure themselves that when they close WordPress comments with comment sync enabled, to close the XF thread as well and vice versa.
