### ISSUE TITLE
ErrorException: [E_NOTICE] Trying to get property 'platform_id' of non-object

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#577]
Issue reported by xPreswa on ticket #14570
```
#0 src/addons/ThemeHouse/XLink/RemoteHandler/Traits/APICall.php(99): XF::handlePhpError(8, '[E_NOTICE] Tryi...', '/home/public/si...', 99, Array)
#1 src/addons/ThemeHouse/XLink/RemoteHandler/Traits/APICall.php(59): ThemeHouse\XWiki\RemoteHandler\Usergroup->addAuthHeader(Array)
#2 src/addons/ThemeHouse/XWiki/RemoteHandler/Usergroup.php(18): ThemeHouse\XWiki\RemoteHandler\Usergroup->callAPI('xwiki-usergroup...')
#3 src/addons/ThemeHouse/XLink/Admin/Controller/Promotion.php(97): ThemeHouse\XWiki\RemoteHandler\Usergroup->getRemoteUserGroups()
#4 src/addons/ThemeHouse/XLink/Admin/Controller/Promotion.php(81): ThemeHouse\XLink\Admin\Controller\Promotion->promotionAddEdit(Object(ThemeHouse\XLink\Entity\Promotion))
#5 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\XLink\Admin\Controller\Promotion->actionAdd(Object(XF\Mvc\ParameterBag))
#6 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\XLin...', 'Add', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XLink\Admin\Controller\Promotion), NULL)
#7 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XLink\Admin\Controller\Promotion), NULL)
#8 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#9 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
#10 src/XF.php(390): XF\App->run()
#11 admin.php(13): XF::runApp('XF\\Admin\\App')
#12 {main}
```

**Comment by LukasWieditz** [comment]
References #575
